# ---- Build stage ----
FROM gradle:8.7-jdk17 AS builder
WORKDIR /app

# Copy build configuration first for better layer caching
COPY build.gradle.kts settings.gradle.kts ./
COPY gradle ./gradle

# Copy sources
COPY src ./src

# Build a fat/distribution jar. installDist produces an app image under build/install.
RUN gradle --no-daemon clean installDist

# ---- Runtime stage ----
FROM eclipse-temurin:17-jre-jammy AS runtime
WORKDIR /app

# Install curl so the container health check can probe /health
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

# Copy the built application from the builder stage
COPY --from=builder /app/build/install/tickets-event-backend ./

ENV PORT=8080
EXPOSE 8080

# The start script is generated by the Gradle application plugin
ENTRYPOINT ["./bin/tickets-event-backend"]
